default: &default
  adapter: postgresql
  username: toodoo
  password: toodoo
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: toodoo_db_dev

test:
  <<: *default
  database: toodoo_db_test

production:
  <<: *default
  database: toodoo_db_prod
